import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';

import SharedLayout from '@/components/SharedLayout';
import './globals.scss';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'OverlayLab',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={poppins.className}>
        <SharedLayout>{children}</SharedLayout>
        <div id='overlay-root' />
      </body>
    </html>
  );
}
